# PowerSync Cloud config (mirrors provisioned cloud instance)
# yaml-language-server: $schema=https://unpkg.com/@powersync/cli-schemas@latest/json-schema/service-config.json

region: us
replication:
  connections:
    - type: postgresql
      name: Default
      password:
        secret_ref: default_password
      uri: postgresql://postgres@db.ejanbkfptbealuwtnfsr.supabase.co:5432/postgres
client_auth:
  jwks:
    keys:
      - kty: oct
        kid: powerchat
        k:
          secret_ref: jwks_keys_powerchat
        alg: HS256
  supabase: false
  additional_audiences: []
  allow_temporary_tokens: true
_type: cloud
name: my-cli-instance
